apiVersion: apps/v1
kind: Deployment
metadata:
  name: operatorhubio
  creationTimestamp: null
spec:
  replicas: 1
  selector: {}
  strategy:
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        deployment-run-id: DEPLOYMENT_RUN_ID
    spec:
      containers:
        - name: catalog
          image: catalog
          imagePullPolicy: Always
          ports:
            - containerPort: 50051
              name: grpc
              protocol: TCP
          livenessProbe:
            exec:
              command:
                - grpc_health_probe
                - -addr=localhost:50051
            failureThreshold: 3
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            exec:
              command:
                - grpc_health_probe
                - -addr=localhost:50051
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 128Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        - name: site
          image: site
          imagePullPolicy: Always
          args:
            - --registry=localhost:50051
            - --log=1
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthz
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          ports:
            - containerPort: 8080
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthz
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          resources:
            limits:
              cpu: 400m
              memory: 512Mi
            requests:
              cpu: 400m
              memory: 512Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
